apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray-deployment
  labels:
    app: v2ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2ray
  template:
    metadata:
      labels:
        app: v2ray
    spec:
      containers:
      - name: v2ray
        image: v2fly/v2fly-core:latest
        ports:
        - containerPort: 8080
        command: ["run", "-c", "/etc/v2ray/config.json"]
        volumeMounts:
        - name: config
          mountPath: /etc/v2ray/config.json
          subPath: config.json
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: v2ray-config
          items:
          - key: "config.json"
            path: "config.json"