apiVersion: v1
kind: Service
metadata:
  name: v2ray
spec:
  type: LoadBalancer
  selector:
    app: v2ray
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-8080
    - protocol: TCP
      port: 6443
      targetPort: 6443
      name: https-6443