name: azure-resource-manager

on:
  push:
    paths:
      - '**'

  workflow_dispatch:

jobs:
  prepare-infrastructure:
    runs-on: ubuntu-latest
    
    name: 'azure-resource-manager'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      
      - uses: actions/checkout@v3

      - name: prepare infrastructure
        run: |
          set -xe
          cd v2ray-aci
          terraform init -lock=false
          terraform plan -lock=false
          terraform apply -auto-approve -lock=false
          #terraform destroy -auto-approve -lock=false