name: rg-001

on:
  push:
    paths:
      - '**'

  workflow_dispatch:

jobs:
  resourcegroups:
    runs-on: ubuntu-latest
    
    name: 'rg-001'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Terraform'
        id: terraform
        run: |
          cd iaas
          terraform init          
          terraform plan
          terraform apply -auto-approve
          terraform destroy -auto-approve
