name: azure-resource-manager

on:
  push:
    paths:
      - '**'

  workflow_dispatch:

jobs:
  prepare-infrastructure:
    runs-on: ubuntu-latest
    
    name: 'azure-resource-manager'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: prepare infrastructure
        uses: actions/checkout@v3
      
      - name: terraform
        run: |
          set -xe
          cd paas
          terraform init          
          terraform plan
          terraform apply -auto-approve
          #terraform destroy -auto-approve
          ls -lth
          KUBECONFIG=`cat kubeconfig`
      
      - name: deploy application
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ KUBECONFIG }}
        run: | 
          set -xe
          kubectl get nodes
